CarRentalCore2/Models/IndvidualButtonPartial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarRentalCore2.Models
{
    public class IndvidualButtonPartial
    {
        public string ButtonType { get; set; }
        public string Action { get; set; }
        public string Glyph { get; set; }
        public string Text { get; set; }

        public int? ServiceID { get; set; }
        public string CustomerID { get; set; }
        public int? CarId { get; set; }

        public string ActionParameters
        {
            get
            {
                if (ServiceID != null && ServiceID != 0)
                {
                    return $"/{ServiceID}";
                }

                if (!string.IsNullOrWhiteSpace(CustomerID))
                {
                    return $"/{CustomerID}";
                }

                if (CarId != null && CarId != 0)
                {
                    return $"/{CarId}";
                }
                return "/";
            }
        }
    }
}

CarRentalCore2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarRentalCore2.Data;
using CarRentalCore2.Models;
using CarRentalCore2.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRentalCore2.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {

        public CarsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        private readonly ApplicationDbContext _dbContext;

        //get index
        public async Task<IActionResult> Index(string userID = null)
        {
            if (string.IsNullOrWhiteSpace(userID))
            {
                //only if guest
                userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel()
            {
                Cars = _dbContext.Cars.Where(c => c.UserId == userID).ToList(),
                User = _dbContext.Users.FirstOrDefault(u => u.Id == userID)
            };

            return View(model);
        }

        //Create Get
        public async Task<IActionResult> Create(string userId)
        {
            Car carToAdd = new Car()
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };

            return View(carToAdd);
        }

        //Creat Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car carToSave)
        {
            if (carToSave == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                _dbContext.Add(carToSave);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = carToSave.UserId });
            }
            return View(carToSave);
        }

        //Details Get
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Details Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Edit Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car carToEdit)
        {
            if (carToEdit == null || id != carToEdit.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _dbContext.Update(carToEdit);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = carToEdit.UserId });
            }
            return View(carToEdit);
        }

        //Details Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Delete Post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCar(int id)
        {
            var car = await _dbContext.Cars.SingleOrDefaultAsync(c => c.Id == id);

            if (car == null)
                return NotFound();

            _dbContext.Cars.Remove(car);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { userId = car.UserId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
        }
    }
}

CarRentalCore2/Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRentalCore2.Data;
using CarRentalCore2.Models;
using CarRentalCore2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRentalCore2.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class ServiceTypesController : Controller
    {
        #region C'tor

        public ServiceTypesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        #endregion

        #region Props

        private readonly ApplicationDbContext _dbContext;

        #endregion

        #region Action Method's

        //Get: ServiceTypes
        public IActionResult Index()
        {
            return View(_dbContext.ServiceTypes.ToList());
        }

        //Get: ServiceTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        //Post: ServiceTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
                _dbContext.ServiceTypes.Add(serviceType);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }

        //Get: ServiceTypes/Details/1
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var serviceType = await _dbContext.ServiceTypes.FirstOrDefaultAsync(s => s.ID == id);

            if (serviceType == null)
                return NotFound();

            return View(serviceType);
        }

        //Get: ServiceTypes/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var serviceType = await _dbContext.ServiceTypes.FirstOrDefaultAsync(s => s.ID == id);

            if (serviceType == null)
                return NotFound();

            return View(serviceType);
        }

        //Post: ServiceTypes/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ServiceType serviceType)
        {
            if (serviceType == null || id != serviceType.ID)
                return NotFound();

            if (ModelState.IsValid)
            {
                _dbContext.Update(serviceType);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(serviceType);
        }

        //Get: ServiceTypes/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var serviceType = await _dbContext.ServiceTypes.FirstOrDefaultAsync(s => s.ID == id);

            if (serviceType == null)
                return NotFound();

            return View(serviceType);
        }

        //Post: ServiceTypes/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var serviceTypeToDelete = await _dbContext.ServiceTypes.FirstOrDefaultAsync(s => s.ID == id);
            _dbContext.ServiceTypes.Remove(serviceTypeToDelete);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region ovveride

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
        }

        #endregion 
    }
}

CarRentalCore2/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRentalCore2.Data;
using CarRentalCore2.Models;
using CarRentalCore2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRentalCore2.Controllers
{
    [Authorize(Roles = SD.AdminEndUser)]
    public class UsersController : Controller
    {
        public UsersController(ApplicationDbContext dbConext)
        {
            _dbContext = dbConext;
        }

        private readonly ApplicationDbContext _dbContext;


        //Get: Users
        public IActionResult Index(string option = null, string search = null)
        {
            var users = _dbContext.Users.ToList();

            if (!string.IsNullOrWhiteSpace(search))
            {
                switch (option)
                {
                    case SD.email:
                        Func<ApplicationUser, bool> emailPredicate = u => u.Email.ToLower().Contains(search.ToLower());
                        users = FilterList(users, emailPredicate);
                        break;

                    case SD.name:
                        Func<ApplicationUser, bool> namePredicate = u => u.FirstName.ToLower().Contains(search.ToLower()) ||
                                                                     u.LastName.ToLower().Contains(search.ToLower());
                        users = FilterList(users, namePredicate);
                        break;

                    case SD.phone:
                        Func<ApplicationUser, bool> phonePredicate = u => u.PhoneNumber.ToLower().Contains(search.ToLower());
                        users = FilterList(users, phonePredicate);
                        break;
                }
            }

            return View(users);
        }

        //Get: Users/Details
        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            ApplicationUser userToFind = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (userToFind == null)
                return NotFound();

            return View(userToFind);
        }

        //Get: Users/Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            ApplicationUser userToFind = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (userToFind == null)
                return NotFound();

            return View(userToFind);
        }

        //post: User/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", user);
            }
            else
            {
                var userToEdit = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == user.Id);

                if (userToEdit == null)
                    return NotFound();

                userToEdit.FirstName = user.FirstName;
                userToEdit.LastName = user.LastName;
                userToEdit.Email = user.Email;
                userToEdit.PhoneNumber = user.PhoneNumber;
                userToEdit.Address = user.Address;
                userToEdit.City = user.City;
                userToEdit.PostalCode = user.PostalCode;

                _dbContext.Update(userToEdit);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        //Get: Users/Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            ApplicationUser userToFind = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (userToFind == null)
                return NotFound();

            return View(userToFind);
        }

        //Post: Users/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfrim(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return NotFound();

            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
                return NotFound();

            var cars = _dbContext.Cars.Where(c => c.UserId == user.Id).ToList();

            foreach (var car in cars)
            {
                var services = _dbContext.Services.Where(s => s.carId == car.Id).ToList();

                _dbContext.Services.RemoveRange(services);
            }

            _dbContext.Cars.RemoveRange(cars);
            _dbContext.Users.Remove(user);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private List<T> FilterList<T>(IEnumerable<T> users, Func<T, bool> predicate)
        {
            return users.Where(predicate).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
        }
    }
}

CarRentalCore2/Views/Shared/_CarDetailsService.cshtml
@model CarRentalCore2.ViewModel.CarAndServicesViewModel

<h4>Car record for customer</h4>

<div class="row form-border">
    <div class="col-sm-5">
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Make" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Make" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="Model" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom:5px;">
                <input asp-for="Model" disabled class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-sm-offset-2">
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="Style" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <input asp-for="Style" disabled class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="Year" class="control-label"></label>
                </div>
                <div class="col-sm-9" style="padding-bottom:5px;">
                    <input asp-for="Year" disabled class="form-control" />
                </div>
            </div>
        </div>    
</div>

CarRentalCore2/Views/Shared/_DisplayPastSevices.cshtml
@model CarRentalCore2.ViewModel.CarAndServicesViewModel
@using CarRentalCore2.Utility
<table class="table table-condensed table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.PastServices.FirstOrDefault().Miles)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.PastServices.FirstOrDefault().Price)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.PastServices.FirstOrDefault().Details)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.PastServices.FirstOrDefault().DateAdded)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.PastServices.FirstOrDefault().ServiceType.Name)
        </th>
        <th>

        </th>
    </tr>

    @foreach (var service in Model.PastServices)
    {
        <tr>
            <td>
                @Html.DisplayFor(m => service.Miles)
            </td>
            <td>
                @Html.DisplayFor(m => service.Price)
            </td>
            <td>
                @Html.DisplayFor(m => service.Details)
            </td>
            <td>
                @Html.DisplayFor(m => service.DateAdded)
            </td>
            <td>
                @Html.DisplayFor(m => service.ServiceType.Name)
            </td>
            <td>
                @if (service.DateAdded.Date == DateTime.Now.Date && User.IsInRole(SD.AdminEndUser))
                {
                    @Html.Partial("_IndvidualButtonPartial",
                        new IndvidualButtonPartial
                        {
                            Action = "Delete",
                            ButtonType="btn-danger",
                            Glyph = "trash",
                            Text = "Delete Button",
                            ServiceID = service.Id
                        })
                }
            </td>
        </tr>
    }
</table>

CarRentalCore2/Views/Shared/_IndvidualButtonPartial.cshtml
@model CarRentalCore2.Models.IndvidualButtonPartial

<a type="button" class="btn btn-sm @Model.ButtonType"
   href="@Url.Action(Model.Action)@Model.ActionParameters">
    <span class="glyphicon glyphicon-@Model.Glyph"></span>
    <span class="sr-only">@Model.Text</span>
</a>

CarRentalCore2/Views/Shared/_Layout.cshtml
@using CarRentalCore2.Utility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRentalCore2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CarRentalCore2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Cars</a></li>
                    @if (User.IsInRole(SD.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="ServiceTypes" asp-action="Index">Service Types</a></li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <footer class="footer">
        <div class="container">
            <p class="text-muted">&copy; 2018 - CarRentalCore2</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CarRentalCore2/Views/Shared/_TableButtonPartial.cshtml
@model CarRentalCore2.Models.IndvidualButtonPartial

<td style="width:150px;">
    <div class="btn-group" role="group">
        @Html.Partial("_IndvidualButtonPartial",
                     new IndvidualButtonPartial
                     {
                         Action = "Edit",
                         ButtonType = "btn-primary",
                         Glyph = "pencil",
                         Text = "Edit",
                         ServiceID = Model.ServiceID,
                         CustomerID = Model.CustomerID,
                         CarId = Model.CarId
                     })

        @Html.Partial("_IndvidualButtonPartial",
                     new IndvidualButtonPartial
                     {
                         Action = "Details",
                         ButtonType = "btn-success",
                         Glyph = "list",
                         Text = "Details",
                         ServiceID = Model.ServiceID,
                         CustomerID = Model.CustomerID,
                         CarId = Model.CarId
                     })

        @Html.Partial("_IndvidualButtonPartial",
                    new IndvidualButtonPartial
                    {
                        Action = "Delete",
                        ButtonType = "btn-danger",
                        Glyph = "trash",
                        Text = "Delete",
                        ServiceID = Model.ServiceID,
                        CustomerID = Model.CustomerID,
                        CarId = Model.CarId
                    }) 
    </div>
<td />