CarRentalCore2/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarRentalCore2.Models
{
    public class Car
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Vin { get; set; }

        [Required]
        public string Make { get; set; }

        [Required]
        public string Model { get; set; }

        public string Style { get; set; }

        [Required]
        public int Year { get; set; }

        [Required]
        public double Miles { get; set; }

        public string Color { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser ApplicationUser { get; set; }
    }
}

CarRentalCore2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarRentalCore2.Data;
using CarRentalCore2.Models;
using CarRentalCore2.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRentalCore2.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {

        public CarsController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        private readonly ApplicationDbContext _dbContext;

        //get index
        public async Task<IActionResult> Index(string userID = null)
        {
            if (string.IsNullOrWhiteSpace(userID))
            {
                //only if guest
                userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel()
            {
                Cars = _dbContext.Cars.Where(c => c.UserId == userID).ToList(),
                User = _dbContext.Users.FirstOrDefault(u => u.Id == userID)
            };

            return View(model);
        }

        //Create Get
        public async Task<IActionResult> Create(string userId)
        {
            Car carToAdd = new Car()
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };

            return View(carToAdd);
        }

        //Creat Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car carToSave)
        {
            if (carToSave == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                _dbContext.Add(carToSave);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = carToSave.UserId });
            }
            return View(carToSave);
        }

        //Details Get
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Details Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Edit Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car carToEdit)
        {
            if (carToEdit == null || id != carToEdit.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _dbContext.Update(carToEdit);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { userId = carToEdit.UserId });
            }
            return View(carToEdit);
        }

        //Details Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var selectedCar = await _dbContext.Cars.Include(u => u.ApplicationUser)
                                    .FirstOrDefaultAsync(c => c.Id == id);

            if (selectedCar == null)
                return NotFound();

            return View(selectedCar);
        }

        //Delete Post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCar(int id)
        {
            var car = await _dbContext.Cars.SingleOrDefaultAsync(c => c.Id == id);

            if (car == null)
                return NotFound();

            _dbContext.Cars.Remove(car);
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { userId = car.UserId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
        }
    }
}

CarRentalCore2/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRentalCore2.Data;
using CarRentalCore2.Models;
using CarRentalCore2.Utility;
using CarRentalCore2.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRentalCore2.Controllers
{
    public class ServicesController : Controller
    {
        public ServicesController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        private readonly ApplicationDbContext _dbContext;

        [Authorize]
        public IActionResult Index(int carId)
        {
            var car = _dbContext.Cars.FirstOrDefault(c => c.Id == carId);
            var model = new CarAndServicesViewModel
            {
                CarId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                Vin = car.Vin,
                Year = car.Year,
                UserId = car.UserId,
                ServiceTypes = _dbContext.ServiceTypes.ToList(),
                PastServices = _dbContext.Services.Where(s => s.carId == carId).ToList()
                                                    .OrderByDescending(s => s.DateAdded),
                Service = new Service()
            };

            return View(model);
        }

        //Get Create
        [Authorize(Roles = SD.AdminEndUser)]
        public IActionResult Create(int carId)
        {
            var car = _dbContext.Cars.FirstOrDefault(c => c.Id == carId);
            var model = new CarAndServicesViewModel
            {
                CarId = car.Id,
                Make = car.Make,
                Model = car.Model,
                Style = car.Style,
                Vin = car.Vin,
                Year = car.Year,
                UserId = car.UserId,
                ServiceTypes = _dbContext.ServiceTypes.ToList(),
                PastServices = _dbContext.Services.Where(s => s.carId == carId).ToList()
                                                    .OrderByDescending(s => s.DateAdded)
                                                    .Take(5),
                Service = new Service()
            };

            return View(model);
        }

        //Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles =SD.AdminEndUser)]
        public async Task<IActionResult> Create(CarAndServicesViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Service.carId = model.CarId;
                model.Service.DateAdded = DateTime.Now;
                _dbContext.Add(model.Service);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Create), new { carId = model.CarId });
            }
            else
            {
                var car = _dbContext.Cars.FirstOrDefault(c => c.Id == model.CarId);
                var newModel = new CarAndServicesViewModel
                {
                    CarId = car.Id,
                    Make = car.Make,
                    Model = car.Model,
                    Style = car.Style,
                    Vin = car.Vin,
                    Year = car.Year,
                    UserId = car.UserId,
                    ServiceTypes = _dbContext.ServiceTypes.ToList(),
                    PastServices = _dbContext.Services.Where(s => s.carId == model.CarId).ToList()
                                                 .OrderByDescending(s => s.DateAdded)
                                                 .Take(5)
                };
                return View(newModel);
            }
        }

        //Get Delete
        [Authorize(Roles = SD.AdminEndUser)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var service = await _dbContext.Services.Include(s => s.Car)
                                                    .Include(s => s.ServiceType)
                                                    .SingleOrDefaultAsync(s => s.Id == id);

            if (service == null)
                return NotFound();

            return View(service);
        }

        //Post Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.AdminEndUser)]
        public async Task<IActionResult> DeleteService(Service model)
        {
            var serviceId = model.Id;
            var carId = model.carId;

            var service = await _dbContext.Services.SingleOrDefaultAsync(s => s.Id == serviceId);

            if (service == null)
                return NotFound();

            _dbContext.Services.Remove(service);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Create), new { carId = carId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _dbContext.Dispose();
            }
        }
    }
}

CarRentalCore2/Views/Cars/Create.cshtml
@model CarRentalCore2.Models.Car
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Add Service Car</h2>
<hr />

<form method="post" asp-action="Create">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Vin" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Vin" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Vin" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Make" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Make" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Model" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Model" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Style" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Style" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Style" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Year" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Year" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Year" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Miles" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Miles" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Miles" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Color" class="custom-label" ></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Color" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Color" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Add Car" class="btn btn-sm btn-primary" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
    <input asp-for="UserId" type="hidden" />
</form>

CarRentalCore2/Views/Cars/Delete.cshtml
@model CarRentalCore2.Models.Car
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Delete Car</h2>
<hr />

<form method="post" asp-action="Delete">
    <div class="form-border">
        <fieldset disabled>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Vin" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Vin" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Make" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Make" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Model" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Model" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Style" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Style" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Year" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Year" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Miles" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Miles" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Color" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input type="text" asp-for="Color" class="form-control" />
                    </div>
                </div>
            </div>
        </fieldset>
        <br />
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
    <input asp-for="UserId" type="hidden" />
</form>

CarRentalCore2/Views/Cars/Details.cshtml
@model CarRentalCore2.Models.Car
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Car Details</h2>
<hr />


<div class="form-border">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Vin" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Vin" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Make" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Make" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Model" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Model" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Style" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Style" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Year" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Year" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Miles" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Miles" class="form-control" disabled />
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Color" class="custom-label"></label>
            </div>
            <div class="col-sm-4">
                <input type="text" asp-for="Color" class="form-control" disabled />
            </div>
        </div>

    </div>
    <br />
    <div class="form-group">
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-primary">Edit</a>
        <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
    </div>
</div>

CarRentalCore2/Views/Cars/Edit.cshtml
@model CarRentalCore2.Models.Car
@{
    ViewData["Title"] = "Edit";
}

<br />
<h2>Edit Car</h2>
<hr />

<form method="post" asp-action="Edit">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Id" type="hidden" />
        <input asp-for="UserId" type="hidden" />
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Vin" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Vin" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Vin" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Make" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Make" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Make" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Model" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Model" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Style" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Style" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Style" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Year" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Year" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Year" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Miles" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Miles" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Miles" class="text-danger"></span>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Color" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input type="text" asp-for="Color" class="form-control" />
                </div>
            </div>

            <span asp-validation-for="Color" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-sm btn-primary" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
    <input asp-for="UserId" type="hidden" />
</form>

CarRentalCore2/Views/Cars/Index.cshtml
@model CarRentalCore2.ViewModel.CarAndCustomerViewModel
@using CarRentalCore2.Utility
@{
    ViewData["Title"] = "Index";
}

<br />
<h2>Car record for customer</h2>
<hr />

<div class="row" style="padding-bottom:80px;">
    <div class="col-sm-6" style="padding-bottom:80px;">
        @* Add Create New Car Button *@
        <a asp-action="Create" asp-route-userID="@Model.User.Id" class="btn btn-sm btn-primary" style="width:150px;">Add new car</a>
    </div>
    <div class="col-sm-6">
        @* display user details *@
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.FirstName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.FirstName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.LastName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.LastName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.PhoneNumber" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.PhoneNumber" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="User.Email" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom:5px;">
                <input asp-for="User.Email" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>

@if (!Model.Cars.Any())
{
    <div class="text-primary form-border">No car found !</div>
}
else
{
    <div class="form-border">
        <table class="table table-condensed table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Vin)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Make)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Model)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Style)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Color)
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var car in Model.Cars)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => car.Vin)
                    </td>
                    <td>
                        @Html.DisplayFor(m => car.Make)
                    </td>
                    <td>
                        @Html.DisplayFor(m => car.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(m => car.Style)
                    </td>
                    <td>
                        @Html.DisplayFor(m => car.Color)
                    </td>
                    @if (User.IsInRole(SD.CustomerEndUser))
                    {
                        <td style="width:100px">
                            <a asp-controller="Services" class="btn btn-sm btn-primary" asp-action="Index" asp-route-carId="@car.Id">
                                <span class="glyphicon glyphicon-wrench"></span>&nbsp; Service History
                            </a>
                        </td>
                    }
                    else
                    {
                        <td style="width:100px">
                            <a class="btn btn-sm btn-success" asp-controller="Services" asp-action="Create" asp-route-carId="@car.Id">
                                <span class="glyphicon glyphicon-plus-sign"></span>&nbsp; Service History
                            </a>
                        </td>
                    }
                    <td>
                        @Html.Partial("_TableButtonPartial", new IndvidualButtonPartial { CarId = car.Id })
                    </td>
                </tr>
            }
        </table>
    </div>
}